INSERT INTO users (email, password_hash, role, created_at)
VALUES ('admin@futurix.io', '$2y$12$0L80XjI7L8uwnymxF6Uf2efiDAflf2LUKgszxztP0BvSWFB7M1RDi', 'admin', NOW());

INSERT INTO projects (slug, project_name, logo_url, description, use_case, challenges, tech_stack_json, compatibility, team_name, team_members_json, links_json, screenshots_json, track, likes_count, status, created_by_user_id, created_at, updated_at)
VALUES
('neon-orbit', 'Neon Orbit', 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=300&q=80', 'A collaborative mission control for mixed reality teams.', 'Enable remote operators to coordinate real-time missions with spatial overlays.', 'Balancing low latency streaming with secure authentication.', '["React","Three.js","WebRTC","Node.js"]', 'web', 'Orbit Labs', '["Lena Park","Omar Singh","Jules Hart"]', '{"github_url":"https://github.com/futurix/neon-orbit","demo_url":"https://demo.futurix.io/neon"}', '["https://images.unsplash.com/photo-1526498460520-4c246339dccb?auto=format&fit=crop&w=800&q=80","https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80"]', 'Spatial Computing', 124, 'approved', 1, NOW(), NOW()),
('pulse-grid', 'Pulse Grid', 'https://images.unsplash.com/photo-1488229297570-58520851e868?auto=format&fit=crop&w=300&q=80', 'Adaptive energy dashboards for smart districts.', 'Give city planners a live view of energy demand and supply anomalies.', 'Integrating heterogeneous sensor streams and forecasting peaks.', '["React","Python","FastAPI","Prophet"]', 'web', 'Gridline', '["Aria Lopez","Mateo Cruz"]', '{"github_url":"https://github.com/futurix/pulse-grid","docs_url":"https://docs.futurix.io/pulse"}', '["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80"]', 'Climate Tech', 86, 'approved', 1, NOW(), NOW()),
('aura-health', 'Aura Health', 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=300&q=80', 'Wellness companion that monitors stress and suggests interventions.', 'Support employees with micro-break guidance and breathing routines.', 'Designing alerts that feel calming instead of intrusive.', '["React","TensorFlow.js","WebAudio"]', 'web', 'Aurora Collective', '["Sasha Kim","Leo Patel","Nadia Chen"]', '{"github_url":"https://github.com/futurix/aura-health","video_url":"https://videos.futurix.io/aura"}', '["https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80"]', 'Health & Wellness', 142, 'approved', 1, NOW(), NOW()),
('quantum-ledger', 'Quantum Ledger', 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=300&q=80', 'Cross-border settlement rails for micro-payments.', 'Reduce friction for creators getting paid internationally.', 'Ensuring compliance while staying chain-agnostic.', '["React","Solidity","Node.js"]', 'web', 'Quanta', '["Riya Sen","Victor Huang"]', '{"github_url":"https://github.com/futurix/quantum-ledger","demo_url":"https://demo.futurix.io/ledger"}', '["https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80"]', 'Web3', 63, 'approved', 1, NOW(), NOW()),
('lumen-scout', 'Lumen Scout', 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=300&q=80', 'AI that scouts innovation trends across research papers.', 'Help founders discover whitespace opportunities.', 'Building reliable extraction pipelines from PDFs.', '["React","Python","LangChain","ElasticSearch"]', 'web', 'Lumen Labs', '["Harper Ray","Noah Malik","Anya Feld"]', '{"github_url":"https://github.com/futurix/lumen-scout","docs_url":"https://docs.futurix.io/lumen"}', '["https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80"]', 'AI Agents', 98, 'approved', 1, NOW(), NOW()),
('terra-sense', 'Terra Sense', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=300&q=80', 'Field analytics for soil and crop health.', 'Empower small farms to optimize irrigation with low-cost sensors.', 'Handling intermittent connectivity from rural devices.', '["React","Go","IoT","Grafana"]', 'web', 'TerraSense', '["Mila Okoro","Evan Ross"]', '{"github_url":"https://github.com/futurix/terra-sense"}', '["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80"]', 'Climate Tech', 71, 'approved', 1, NOW(), NOW()),
('nova-mentor', 'Nova Mentor', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=300&q=80', 'Mentorship matchmaking for hackathons.', 'Pair participants with experts based on skill gaps.', 'Keeping recommendations fair across tracks.', '["React","Node.js","PostgreSQL"]', 'web', 'Nova Team', '["Diego Park","Isla Morgan","Soren Lee"]', '{"github_url":"https://github.com/futurix/nova-mentor"}', '["https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80"]', 'AI Agents', 54, 'approved', 1, NOW(), NOW()),
('skyforge', 'Skyforge', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=300&q=80', 'Drone route optimizer for emergency deliveries.', 'Speed up dispatch planning during natural disasters.', 'Balancing battery constraints with time-critical routes.', '["React","Python","GraphQL"]', 'web', 'Skyforge', '["Priya Nair","Jonas Reed"]', '{"github_url":"https://github.com/futurix/skyforge","demo_url":"https://demo.futurix.io/skyforge"}', '["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=80"]', 'Health & Wellness', 77, 'approved', 1, NOW(), NOW());
